### ISSUE TITLE
Ability to customize source links

### ISSUE THREAD

**Issue by arichiardi** [borkdude/quickdoc#10]
Hi there, we are evaluating `quickdoc` (against `codox`) for its speed and we are very happy with that so far.

One improvement we were thinking of was to add something generic for pointing to source (I see `:github/repo` is there but unfortunately we use DevOps).

The DevOps format for pointing to a file line is something like:

`https://dev.azure.com/company/_git/project?path=/path/src/auth/jwt_test.clj&version=GBmain&_a=contents&line=18&lineEnd=19&lineStartColumn=1&lineEndColumn=1&lineStyle=plain`

(it's cool that it has the ability to point to a column but we never really use that)

What do you think about that? 

Should it be a template like in [codox](https://github.com/weavejester/codox#source-links)?

**Comment by borkdude** [comment]
@arichiardi I think something like that would be good.

**Comment by arichiardi** [comment]
I was planning on taking a look over the weekend, I definitely can try thanks so so much!

Jun 23, 2022 12:52:33 PM Michiel Borkent ***@***.***>:
