### ISSUE TITLE
Improve rendering performance

### ISSUE THREAD

**Issue by arichiardi** [borkdude/quickdoc#11]
Hi there again, this is an issue that is only tangential to `quickdoc` - the fact that it produces a big `.md` does not work great for projects with a lot of namespaces as the problem is that any Markdown renderer would slow to a crawl when opening it.

Possible solutions:
  * Ability to include/exclude namespaces
  * Ability to associate namespaces with output files (landing page is the toc that will point to them)
  
I am ok with a "won't fix" answer given the project goals :smile: 

Any other nice `bb`-friendly suggestion for bigger projects?

**Comment by borkdude** [comment]
@arichiardi Yes, you can just list only the namespace _files_ that you want to be part of the API in `:source-paths`, they can be specific .clj files, not just directories.

**Comment by borkdude** [comment]
You can also call quickdoc multiple times, once per namespace to generate one file per namespace. The output file is optional, if you set it to `nil` it won't write to a file. Quickdoc returns the markdown in the return value so you can do your own thing with it. If that is not sufficient, please reach out. If it is, then the issue can be closed.

**Comment by borkdude** [comment]
You can see an example of not using an outfile but doing a manual thing here:

https://github.com/babashka/sci/blob/3d7262ce7f5103484d8a4e00a7456f3bf4aebccf/bb.edn#L24
