### ISSUE TITLE
Quickdoc captures vars defined in comment blocks

### ISSUE THREAD

**Issue by bsless** [borkdude/quickdoc#14]
This is probably undesirable behavior

**Comment by bsless** [comment]
see https://github.com/bsless/tools.jcmd.jfr/commit/3fcbe19da68835f943410dc184396527fcfd71f0#diff-b161966f7254af9c9c5382e859495c69622843e4602a6bb4208e08134e660121R35

**Comment by borkdude** [comment]
Good point. This can be easily fixed by adding `:skip-comments true` [here](https://github.com/borkdude/quickdoc/blob/a8068f1c8b13e09a2966804213fc41dd813de18e/src/quickdoc/api.cljc#L43). PR welcome.
